# Generated by Django 5.2.1 on 2025-06-25 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_men'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accoutn',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_key', to='main.profile'),
        ),
    ]
